# Generated by Django 4.1.1 on 2022-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cartitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
