# Generated by Django 4.1.1 on 2022-09-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_id_shoppingsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empty'), (2, 'Active'), (3, 'Purchased')], default=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
