# Generated by Django 4.1.1 on 2022-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shoppingsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empty'), (2, 'Active'), (3, 'Purchased')], verbose_name='status'),
        ),
    ]
