# Generated by Django 4.1.1 on 2022-09-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_shoppingsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingsession',
            name='status',
        ),
    ]
