# Generated by Django 4.1.1 on 2022-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_shoppingsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
