# Generated by Django 4.1.1 on 2022-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_shoppingsession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingsession',
            name='total',
        ),
        migrations.AddField(
            model_name='shoppingsession',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empty'), (2, 'Active'), (3, 'Purchased')], default=1, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingsession',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
