# Generated by Django 4.1.1 on 2022-09-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_shoppingsession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
    ]
