# Generated by Django 4.1.1 on 2022-09-24 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_botuser_created_at_remove_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2022-09-22 16:10:58.048458'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
