# Generated by Django 4.1.1 on 2022-09-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_botuser_created_at_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='session_id',
            new_name='session',
        ),
    ]
